name: agents
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - expat=2.5.0
  - libffi=3.4.4
  - openssl=3.0.11
  - pip=23.3
  - python=3.12.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - anyio==4.0.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==23.1.0
      - binaryornot==0.4.4
      - blinker==1.6.3
      - cachetools==5.3.2
      - certifi==2023.7.22
      - chardet==5.2.0
      - charset-normalizer==3.3.1
      - click==8.1.7
      - comm==0.1.4
      - contourpy==1.1.1
      - cookiecutter==2.4.0
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - executing==2.0.1
      - fastjsonschema==2.18.1
      - filelock==3.13.0
      - flask==3.0.0
      - fonttools==4.43.1
      - h11==0.14.0
      - humanize==4.8.0
      - idna==3.4
      - ipykernel==6.26.0
      - ipython==8.17.1
      - ipyvue==1.10.1
      - ipyvuetify==1.8.10
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.5.0
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - markdown==3.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mesa==2.1.2
      - mesa-viz-tornado==0.1.1
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - numpy==1.26.1
      - packaging==23.2
      - pandas==2.1.2
      - parso==0.8.3
      - pexpect==4.8.0
      - pillow==10.1.0
      - platformdirs==3.11.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pymdown-extensions==10.3.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-slugify==8.0.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - reacton==1.7.2
      - referencing==0.30.2
      - requests==2.31.0
      - rich==13.6.0
      - rich-click==1.7.0
      - rpds-py==0.10.6
      - six==1.16.0
      - sniffio==1.3.0
      - solara==1.22.0
      - stack-data==0.6.3
      - starlette==0.31.1
      - text-unidecode==1.3
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.13.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.7
      - uvicorn==0.23.2
      - watchdog==3.0.0
      - wcwidth==0.2.8
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
